# fly.toml app configuration file generated for craft-discord-bot on 2025-08-16T19:15:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'craft-discord-bot'
primary_region = 'atl'

[build]
  builder = 'paketobuildpacks/builder:base'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
app = "python main.py"
